Repository O-n-Logistics/ssg-deal-BE, pull requests merged in 2025-04, with the labels that each got.

#9 feat: api gateway
  gateway_service/build.gradle
  gateway_service/src/main/java/on/ssgdeal/gateway_service/application/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/application/service/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/application/service/dto/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/configuration/CommonConfig.java
  gateway_service/src/main/java/on/ssgdeal/gateway_service/configuration/JasyptConfig.java
  gateway_service/src/main/java/on/ssgdeal/gateway_service/domain/entity/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/domain/enums/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/domain/repository/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/domain/vo/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/exception/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/infrastructure/client/domain_service_name/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/infrastructure/client/domain_service_name/dto/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/infrastructure/client/domain_service_name/feign/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/infrastructure/filter/AuthGlobalFilter.java
  gateway_service/src/main/java/on/ssgdeal/gateway_service/infrastructure/persistence/jpa/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/infrastructure/persistence/jpa/querydsl/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/infrastructure/persistence/repository/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/presentation/dto/CommonResponse.java
  gateway_service/src/main/java/on/ssgdeal/gateway_service/presentation/external/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/presentation/external/dto/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/presentation/internal/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/presentation/internal/dto/.gitkeep
  gateway_service/src/main/java/on/ssgdeal/gateway_service/presentation/internal/dto/AuthValidateResponse.java
  gateway_service/src/main/resources/application.properties
  gateway_service/src/main/resources/application.yml
Labels: ✨ Feature

#18 feat: 결제 승인 요청 기능
  payment_service/src/main/java/on/ssgdeal/payment_service/application/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentProcessorService.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentProcessorServiceImpl.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentService.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentServiceImpl.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/dto/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/dto/request/OrderPaymentRequestDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/dto/response/OrderPaymentResponseDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/configuration/PaymentExceptionInterceptor.java
  payment_service/src/main/java/on/ssgdeal/payment_service/configuration/PaymentLoggingInterceptor.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/entity/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/entity/Payment.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/enums/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/enums/PaymentFailReason.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/enums/PaymentMethod.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/enums/PaymentStatus.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/enums/PaymentType.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/repository/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/repository/PaymentRepository.java
  payment_service/src/main/java/on/ssgdeal/payment_service/exception/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/exception/PaymentException.java
  payment_service/src/main/java/on/ssgdeal/payment_service/exception/PaymentExceptionCode.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/PaymentClient.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/PaymentProperties.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/dto/request/PaymentConfirmRequestDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/dto/response/PaymentConfirmResponseDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/dto/response/PaymentFailResponseDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/persistence/jpa/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/persistence/jpa/PaymentJpaRepository.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/persistence/repository/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/persistence/repository/PaymentRepositoryImpl.java
  payment_service/src/main/java/on/ssgdeal/payment_service/presentation/external/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/presentation/external/PaymentController.java
  payment_service/src/main/java/on/ssgdeal/payment_service/presentation/external/dto/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/presentation/external/dto/OrderPaymentRequest.java
  payment_service/src/main/resources/application.yml
Labels: ✨ Feature

#23 feat: promotion service - 종료된 프로모션 상세 조회 및 진행 중인 프로모션 상세 조회 구현
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/PromotionService.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/PromotionServiceImpl.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/GetFinishedPromotionDetailResponseDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/GetInProgressPromotionDetailResponseDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/entity/dto/GetInProgressPromotionDetailDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/repository/PromotionRepository.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/exception/PromotionException.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/exception/PromotionExceptionCode.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/init/init.sql
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/jpa/JpaPromotionRepository.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/jpa/querydsl/QueryDslPromotionRepository.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/jpa/querydsl/QueryDslPromotionRepositoryImpl.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/repository/PromotionRepositoryImpl.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/presentation/external/PromotionController.java
  promotion_service/src/test/java/on/ssgdeal/promotion_service/application/service/PromotionServiceImplTest.java
Labels: ✨ Feature

#29 feat: 결제 전체 및 부분 취소, 결제 내역 조회 기능 구현
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/OrderService.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentProcessorService.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentProcessorServiceImpl.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentService.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/PaymentServiceImpl.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/dto/request/OrderPaymentPartialCancelRequestDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/dto/response/GetPaymentsResponseDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/dto/response/OrderPaymentCancelResponseDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/application/service/dto/response/OrderPaymentPartialCancelResponseDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/entity/Payment.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/enums/PaymentCancelReason.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/enums/PaymentResult.java
  payment_service/src/main/java/on/ssgdeal/payment_service/domain/repository/PaymentRepository.java
  payment_service/src/main/java/on/ssgdeal/payment_service/exception/PaymentException.java
  payment_service/src/main/java/on/ssgdeal/payment_service/exception/PaymentExceptionCode.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/PaymentClient.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/dto/request/PaymentCancelRequestDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/dto/request/PaymentPartialCancelRequestDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/TossPaymentClient/dto/response/PaymentCancelResponseDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/domain_service_name/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/domain_service_name/dto/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/domain_service_name/feign/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/domain_service_name/feign/dto/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/order/OrderServiceImpl.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/order/dto/.gitkeep
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/order/feign/OrderServiceFeignClient.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/order/feign/dto/CreateOrderPaymentFailRequestDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/order/feign/dto/CreateOrderPaymentSuccessRequestDto.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/order/feign/dto/GetValidTotalOrderId.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/persistence/jpa/PaymentJpaRepository.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/persistence/repository/PaymentRepositoryImpl.java
  payment_service/src/main/java/on/ssgdeal/payment_service/presentation/external/PaymentController.java
  payment_service/src/main/java/on/ssgdeal/payment_service/presentation/internal/PaymentInternalController.java
  payment_service/src/test/java/on/ssgdeal/payment_service/application/fixture/FixtureFactory.java
  payment_service/src/test/java/on/ssgdeal/payment_service/application/service/PaymentProcessorServiceImplTest.java
Labels: ✅ Test, ✨ Feature

#35 feat: OrderService Cart Delete 엔드포인트 스펙 변경에 따른 DTO 변경
  order_service/src/main/java/on/ssgdeal/order_service/infrastructure/client/cart/feign/dtos/ClearCartRequestDto.java
Labels: ✨ Feature

#14 feat: notification service - 주문 알림 생성 구현
  .gitignore
  notification_service/build.gradle
  notification_service/src/main/java/on/ssgdeal/notification_service/application/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/NotificationService.java
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/NotificationServiceImpl.java
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/SlackClient.java
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/dto/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/dto/CreateNotificationRequestDto.java
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/dto/CreateNotificationResponseDto.java
  notification_service/src/main/java/on/ssgdeal/notification_service/application/service/dto/SendSlackNotificationRequestDto.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/entity/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/entity/Notification.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/entity/NotificationRecord.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/entity/NotificationTemplate.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/entity/dto/CreateNotificationDto.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/enums/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/enums/NotificationStatus.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/enums/NotificationTemplateType.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/repository/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/repository/NotificationRepository.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/repository/NotificationTemplateRepository.java
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/vo/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/domain/vo/SlackEmail.java
  notification_service/src/main/java/on/ssgdeal/notification_service/exception/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/exception/NotificationException.java
  notification_service/src/main/java/on/ssgdeal/notification_service/exception/NotificationExceptionCode.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/domain_service_name/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/domain_service_name/dto/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/domain_service_name/feign/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/domain_service_name/feign/dto/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/slack/SlackClientImpl.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/slack/config/WebClientConfig.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/slack/converter/SlackTimestampToKSTConverter.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/slack/dto/SendNotificationRequest.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/client/slack/dto/SlackUserInfoResponse.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/persistence/jpa/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/persistence/jpa/NotificationJpaRepository.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/persistence/jpa/NotificationTemplateJpaRepository.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/persistence/repository/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/persistence/repository/NotificationRepositoryImpl.java
  notification_service/src/main/java/on/ssgdeal/notification_service/infrastructure/persistence/repository/NotificationTemplateRepositoryImpl.java
  notification_service/src/main/java/on/ssgdeal/notification_service/presentation/internal/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/presentation/internal/NotificationInternalController.java
  notification_service/src/main/java/on/ssgdeal/notification_service/presentation/internal/dto/.gitkeep
  notification_service/src/main/java/on/ssgdeal/notification_service/presentation/internal/dto/CreateNotificationRequest.java
  notification_service/src/main/java/on/ssgdeal/notification_service/presentation/internal/dto/mapper/NotificationPresentationMapper.java
  notification_service/src/main/resources/application.yml
  notification_service/src/test/java/on/ssgdeal/notification_service/NotificationServiceImplApplicationTests.java
  notification_service/src/test/java/on/ssgdeal/notification_service/application/service/NotificationServiceImplIntegrationTest.java
  notification_service/src/test/java/on/ssgdeal/notification_service/application/service/NotificationServiceImplUnitTest.java
Labels: ⚙ Setting, ✨ Feature, 📃 Docs

#41 deploy: 각 패키지에 배포 위한 Dockerfile 생성
  auth_service/Dockerfile
  cart_service/Dockerfile
  config_service/Dockerfile
  eureka_server/Dockerfile
  gateway_service/Dockerfile
  inquiry_service/Dockerfile
  notification_service/Dockerfile
  order_service/Dockerfile
  payment_service/Dockerfile
  promotion_service/Dockerfile
  user_service/Dockerfile
Labels: 🌏 Deploy

#45 fix: GetProductStockRequestDto.java 파일 누락 해결
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/product/GetProductStockRequestDto.java
Labels: 🐞 BugFix

#49 refactor: order service Command Pattern 적용
  common/src/main/java/on/ssgdeal/common/command/Command.java
  common/src/main/java/on/ssgdeal/common/command/CommandFactory.java
  common/src/main/java/on/ssgdeal/common/command/ScopedCommandInvoker.java
  order_service/src/main/java/on/ssgdeal/order_service/application/command/CreateOrderCommand.java
  order_service/src/main/java/on/ssgdeal/order_service/application/command/OrderCommandFactory.java
  order_service/src/main/java/on/ssgdeal/order_service/application/command/support/DestinationValidator.java
  order_service/src/main/java/on/ssgdeal/order_service/application/command/support/OrderCommandSupport.java
  order_service/src/main/java/on/ssgdeal/order_service/application/command/support/ProductValidator.java
  order_service/src/main/java/on/ssgdeal/order_service/application/command/support/StockManager.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/CancelOrderRequestDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/CancelOrderResponseDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/CancelTotalOrderRequestDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/CancelTotalOrderResponseDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/CreateOrderRequestDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/CreateUserInfoDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/GetTotalOrderDetailResponseDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/GetTotalOrdersResponseDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/LoginUserInfoDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/TotalOrderProductInfo.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/UpdateCancelOrderSuccessRequestDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/UpdateTotalOrderFailRequestDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/dto/UpdateTotalOrderSuccessRequestDto.java
  order_service/src/main/java/on/ssgdeal/order_service/application/service/OrderService.java
  order_service/src/main/java/on/ssgdeal/order_service/application/service/OrderServiceImpl.java
  order_service/src/main/java/on/ssgdeal/order_service/configuration/SagaConfig.java
  order_service/src/main/java/on/ssgdeal/order_service/domain/entity/Orderer.java
  order_service/src/main/java/on/ssgdeal/order_service/domain/entity/dtos/CreateOrdererDto.java
  order_service/src/main/java/on/ssgdeal/order_service/domain/entity/dtos/mapper/TotalOrderEntityLayerMapper.java
  order_service/src/main/java/on/ssgdeal/order_service/exception/OrderException.java
  order_service/src/main/java/on/ssgdeal/order_service/exception/OrderExceptionCode.java
  order_service/src/main/java/on/ssgdeal/order_service/infrastructure/client/slack/feign/dtos/OrderCompleteSendSlackRequestDto.java
  order_service/src/main/java/on/ssgdeal/order_service/presentation/external/OrderController.java
  order_service/src/main/java/on/ssgdeal/order_service/presentation/external/dto/CreateOrderRequest.java
  order_service/src/main/java/on/ssgdeal/order_service/presentation/internal/OrderInternalController.java
  order_service/src/main/java/on/ssgdeal/order_service/presentation/internal/dto/UpdateCancelOrderSuccessRequest.java
  order_service/src/main/java/on/ssgdeal/order_service/presentation/internal/dto/UpdateTotalOrderFailRequest.java
  order_service/src/main/java/on/ssgdeal/order_service/presentation/internal/dto/UpdateTotalOrderSuccessRequest.java
  order_service/src/test/java/on/ssgdeal/order_service/application/service/OrderServiceImplTest.java
Labels: 🔨 Refactor

#58 feat: promotion service - 프로모션 생성 API 및 테스트 데이터 생성 구현
  common/src/main/java/on/ssgdeal/common/pageable/enums/PageSortBy.java
  notification_service/src/main/resources/application.yml
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/PromotionService.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/PromotionServiceImpl.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/CreateCompanyRequestDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/CreatePromotionRequestDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/CreatePromotionResponseDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/entity/Company.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/entity/Promotion.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/entity/dto/CreateCompanyDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/entity/dto/CreatePromotionDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/repository/PromotionRepository.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/jpa/PromotionJpaRepository.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/jpa/querydsl/PromotionQueryDslRepositoryImpl.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/repository/PromotionRepositoryImpl.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/presentation/dto/CreateCompanyRequest.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/presentation/dto/CreatePromotionRequest.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/presentation/dto/mapper/PromotionPresentationMapper.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/presentation/external/PromotionController.java
  promotion_service/src/main/resources/application.yml
  promotion_service/src/test/java/on/ssgdeal/promotion_service/application/service/PromotionServiceImplTest.java
Labels: ✨ Feature, 🔨 Refactor

#57 refactor: Promotion의 Product 업데이트 로직 중 재고 증감 로직에 대해 Strategy Pattern 적용
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/ProductServiceImpl.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/StockService.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/mapper/ProductApplicationMapper.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/stock/UpdateStockRequestDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/dto/stock/UpdateStockResponseDto.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/strategy/DecreaseStockStrategy.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/strategy/IncreaseStockStrategy.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/application/service/strategy/StockStrategy.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/enums/StockOperation.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/domain/repository/ProductRepository.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/jpa/ProductJpaRepository.java
  promotion_service/src/main/java/on/ssgdeal/promotion_service/infrastructure/persistence/repository/ProductRepositoryImpl.java
  promotion_service/src/test/java/on/ssgdeal/promotion_service/application/service/ProductServiceImplTest.java
Labels: 🔨 Refactor

#67 fix: 결제 수단에 따른 메소드 선택 시 전략 패턴을 사용하는 과정에서 발생한 버그 수정
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/PaymentClient/strategy/PaymentStrategyFactory.java
  payment_service/src/main/java/on/ssgdeal/payment_service/infrastructure/client/PaymentClient/strategy/TossPaymentStrategy.java
Labels: 🐞 BugFix

#68 fix: 패스포트 필터가 적용되지 말아야 할 부분에도 적용되는 문제 수정
  common/src/main/java/on/ssgdeal/common/web/filter/PassportFilter.java
Labels: 🐞 BugFix
